# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-07 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YsArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=20)),
                ('content', models.TextField(default='')),
                ('time', models.IntegerField(default=0)),
            ],
        ),
    ]
