# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-19 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syapp', '0002_auto_20181118_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.CharField(default='', max_length=255)),
                ('createtime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
