# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-05 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syapp', '0003_logs'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
