# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-16 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syapp', '0004_usermain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ysarticle',
            name='createtime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
